name: MPACTPy Testing

on:
  push:
  schedule:
    # Run every day at 8:00 AM UTC (3:00 AM CDT)
    - cron: '0 8 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Up Python and Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        channels: conda-forge

    - name: Set Up and Configure Environment
      run: |
        conda install -n base -y mamba -c conda-forge
        mamba create -n openmc-env -y python=3.11 openmc hdf5 mpi4py numpy scipy pandas -c conda-forge
        source $(conda info --base)/etc/profile.d/conda.sh && conda activate openmc-env
        python -m pip install pylint pytest openmc_data_downloader

    - name: Download and Set Up OpenMC Cross Sections
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh && conda activate openmc-env
        mkdir -p $HOME/openmc-xs
        openmc_data_downloader -l ENDFB-7.1-NNDC -d $HOME/openmc-xs
        echo "OPENMC_CROSS_SECTIONS=$HOME/openmc-xs/cross_sections.xml" >> $GITHUB_ENV

    - name: Install and Test MPACTPy
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh && conda activate openmc-env
        which openmc
        openmc --version
        pytest -v -s --maxfail=1
        python -m pylint ./mpactpy
